// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw5mjsdiHadCmKghu1pAW8BbFKPFm7pwE',
    appId: '1:1070901561087:web:340995d9f78eca9d6f6eca',
    messagingSenderId: '1070901561087',
    projectId: 'app-actualizacion-prueba',
    authDomain: 'app-actualizacion-prueba.firebaseapp.com',
    storageBucket: 'app-actualizacion-prueba.firebasestorage.app',
    measurementId: 'G-MCNQNNB400',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR50hIU8D7F5eiEJMYjvdyyae6scP3s5E',
    appId: '1:1070901561087:android:33d06f47ec120be36f6eca',
    messagingSenderId: '1070901561087',
    projectId: 'app-actualizacion-prueba',
    storageBucket: 'app-actualizacion-prueba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXR4FoOdTgQuSxihfNf-Bw-tg0ThoFEe4',
    appId: '1:1070901561087:ios:0057a39dce9021196f6eca',
    messagingSenderId: '1070901561087',
    projectId: 'app-actualizacion-prueba',
    storageBucket: 'app-actualizacion-prueba.firebasestorage.app',
    iosBundleId: 'com.example.marcador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXR4FoOdTgQuSxihfNf-Bw-tg0ThoFEe4',
    appId: '1:1070901561087:ios:0057a39dce9021196f6eca',
    messagingSenderId: '1070901561087',
    projectId: 'app-actualizacion-prueba',
    storageBucket: 'app-actualizacion-prueba.firebasestorage.app',
    iosBundleId: 'com.example.marcador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw5mjsdiHadCmKghu1pAW8BbFKPFm7pwE',
    appId: '1:1070901561087:web:70e69612d50bb59e6f6eca',
    messagingSenderId: '1070901561087',
    projectId: 'app-actualizacion-prueba',
    authDomain: 'app-actualizacion-prueba.firebaseapp.com',
    storageBucket: 'app-actualizacion-prueba.firebasestorage.app',
    measurementId: 'G-7D47R0JJYF',
  );
}
